# Generated by Django 5.2.5 on 2025-10-08 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recompute_plan_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacao',
            options={'ordering': ['-data_validade'], 'verbose_name': 'certificação', 'verbose_name_plural': 'certificações'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterModelOptions(
            name='dadosbancarios',
            options={'verbose_name': 'dado bancário', 'verbose_name_plural': 'dados bancários'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['nome'], 'verbose_name': 'módulo', 'verbose_name_plural': 'módulos'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterUniqueTogether(
            name='dadosbancarios',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='data_abertura',
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='entidade_emissora',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Entidade Emissora'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='numero_registro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Registro'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='politica_privacidade',
            field=models.TextField(blank=True, default='', verbose_name='Política de Privacidade (HTML/Markdown)'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='termos_uso',
            field=models.TextField(blank=True, default='', verbose_name='Termos de Uso (HTML/Markdown)'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo / Departamento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome Completo do Contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='chave_pix',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='digito',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Dígito'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='empresadocumentoversao',
            name='competencia',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Competência (MM/AAAA)'),
        ),
        migrations.AlterField(
            model_name='empresadocumentoversao',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ponto_referencia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='enderecoadicional',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='enderecoadicional',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enderecoadicional',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='enderecoadicional',
            name='ponto_referencia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enderecoadicional',
            name='tipo',
            field=models.CharField(choices=[('COB', 'Cobrança'), ('ENT', 'Entrega'), ('OUTRO', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Módulo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cnae_principal',
            field=models.CharField(blank=True, default='', help_text='Código CNAE da atividade principal', max_length=10, verbose_name='CNAE Principal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='codigo_interno',
            field=models.CharField(blank=True, default='', help_text='Código interno para identificação da empresa', max_length=20, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='data_fundacao',
            field=models.DateField(blank=True, help_text='Data de fundação da empresa (quando PJ)', null=True, verbose_name='Data de Fundação'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email_comercial',
            field=models.EmailField(blank=True, default='', help_text='E-mail específico para questões comerciais', max_length=254, verbose_name='E-mail Comercial'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email_financeiro',
            field=models.EmailField(blank=True, default='', help_text='E-mail específico para questões financeiras', max_length=254, verbose_name='E-mail do Financeiro'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email_tecnico',
            field=models.EmailField(blank=True, default='', help_text='E-mail específico para questões técnicas', max_length=254, verbose_name='E-mail Técnico'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('FUNDAMENTAL_INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL_COMPLETO', 'Ensino Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Ensino Médio Incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR_INCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo'), ('POS_GRADUACAO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('NA', 'Não Aplicável')], default='', max_length=50, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('U', 'União Estável'), ('O', 'Outro')], default='', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='inscricao_estadual',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='inscricao_municipal',
            field=models.CharField(blank=True, default='', help_text='Número de inscrição municipal da empresa (se aplicável)', max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='inscricao_suframa',
            field=models.CharField(blank=True, default='', help_text='Número de inscrição na SUFRAMA, se aplicável', max_length=20, verbose_name='Inscrição SUFRAMA'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='naturalidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Naturalidade (Cidade de Nascimento)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome_contato_principal',
            field=models.CharField(blank=True, default='', help_text='Nome da pessoa responsável pela empresa', max_length=200, verbose_name='Nome do Responsável Principal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome_responsavel_comercial',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Responsável Comercial'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome_responsavel_financeiro',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Responsável Financeiro'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nome_responsavel_tecnico',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Responsável Técnico'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Informações adicionais relevantes sobre a empresa.', verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='porte_empresa',
            field=models.CharField(blank=True, choices=[('MEI', 'Microempreendedor Individual'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('MEDIA', 'Empresa de Médio Porte'), ('GRANDE', 'Empresa de Grande Porte'), ('NA', 'Não Aplicável')], default='', max_length=10, verbose_name='Porte da Empresa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='profissao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ramo_atividade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ramo de Atividade Principal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='razao_social',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('SIMPLES', 'Simples Nacional'), ('PRESUMIDO', 'Lucro Presumido'), ('REAL', 'Lucro Real'), ('MEI', 'Microempreendedor Individual')], default='', max_length=20, verbose_name='Regime Tributário'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Não informar')], default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telefone_comercial',
            field=models.CharField(blank=True, default='', help_text='Telefone específico do setor comercial', max_length=20, verbose_name='Telefone Comercial'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telefone_emergencia',
            field=models.CharField(blank=True, default='', help_text='Telefone para contato em emergências', max_length=20, verbose_name='Telefone de Emergência'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telefone_financeiro',
            field=models.CharField(blank=True, default='', help_text='Telefone específico do setor financeiro', max_length=20, verbose_name='Telefone do Financeiro'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='telefone_secundario',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone Secundário'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Site / Website'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='Número do WhatsApp para contato', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='tenantdocumento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CONTRATO', 'Contrato'), ('RG', 'RG'), ('CPF', 'CPF'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tenantdocumento',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='URL do Documento'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viúvo(a)'), ('U', 'União Estável'), ('O', 'Outro')], default='', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='naturalidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Naturalidade (Cidade de Nascimento)'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='profissao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='tenantpessoafisica',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='email_financeiro',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do Financeiro'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='inscricao_estadual',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='inscricao_municipal',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='porte_empresa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Porte da Empresa'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='ramo_atividade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ramo de Atividade'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='telefone_financeiro',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone do Financeiro'),
        ),
        migrations.AlterField(
            model_name='tenantpessoajuridica',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Site / Website'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo / Função'),
        ),
    ]
