# Generated by Django 5.2.5 on 2025-10-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cliente', '0003_portalclienteconfiguracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacliente',
            options={'ordering': ('-created_at',), 'verbose_name': 'Conta Cliente', 'verbose_name_plural': 'Contas Cliente'},
        ),
        migrations.AlterModelOptions(
            name='documentoportalcliente',
            options={'ordering': ('-created_at',), 'verbose_name': 'Documento Portal Cliente', 'verbose_name_plural': 'Documentos Portal Cliente'},
        ),
    ]
