# Generated by Django 5.2.5 on 2025-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='bloco',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Bloco/Torre'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
    ]
