# Generated by Django 5.2.5 on 2025-10-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('-id',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='documentocliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='nome_documento',
        ),
        migrations.RemoveField(
            model_name='documentocliente',
            name='tipo',
        ),
    ]
